# Generated by Django 5.0.3 on 2024-04-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('CUSTOMER', 'customer'), ('ADMIN', 'admin')], max_length=50)),
                ('avatar', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
