# Generated by Django 5.0.3 on 2024-04-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('NONE', 'none'), ('PERCENT', 'percent'), ('AMOUNT', 'amount')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.FloatField(default=0),
        ),
    ]
